"""Exact checks of the fixed-level strong-drive energy through order one.

No matrix diagonalization is used.  Operators act algebraically on a formal
Bogoliubov number state |n>; the finite dictionaries contain only the shifts
generated by the displayed cubic and quartic monomials.
"""

import sympy as sp


def _add(left, right):
    result = dict(left)
    for shift, value in right.items():
        result[shift] = result.get(shift, 0) + value
    return result


def _scale(states, factor):
    return {shift: factor * value for shift, value in states.items()}


def corrections():
    n = sp.symbols("n", integer=True, nonnegative=True)
    delta = sp.symbols("delta", real=True)
    eps = sp.symbols("eps", positive=True)
    sqrt3 = sp.sqrt(3)

    # At r=infinity: b=C*c+S*c_dagger, with tanh(2 theta)=-1/2.
    C = sp.sqrt((2 / sqrt3 + 1) / 2)
    S = -sp.sqrt((2 / sqrt3 - 1) / 2)
    assert sp.simplify(C**2 - S**2 - 1) == 0
    assert sp.simplify(2 * C * S + 1 / sqrt3) == 0

    def annihilate(states):
        return {
            shift - 1: value * sp.sqrt(n + shift)
            for shift, value in states.items()
        }

    def create(states):
        return {
            shift + 1: value * sp.sqrt(n + shift + 1)
            for shift, value in states.items()
        }

    def b(states):
        return _add(_scale(annihilate(states), C), _scale(create(states), S))

    def bdag(states):
        return _add(_scale(create(states), C), _scale(annihilate(states), S))

    def apply_word(word):
        states = {0: sp.Integer(1)}
        for operator in reversed(word):
            states = operator(states)
        return states

    # O3=bdag^2*b+bdag*b^2 and O4=(1/2)bdag^2*b^2.
    o3 = _add(apply_word((bdag, bdag, b)), apply_word((bdag, b, b)))
    o4 = _scale(apply_word((bdag, bdag, b, b)), sp.Rational(1, 2))
    delta4 = sp.simplify(o4[0])
    delta3 = sp.simplify(
        sum(matrix_element**2 / (-sqrt3 * shift)
            for shift, matrix_element in o3.items())
    )

    expected4 = (
        18 * n**2 + (18 - 16 * sqrt3) * n + 15 - 8 * sqrt3
    ) / 24
    expected3 = -(
        30 * n**2 + (30 - 24 * sqrt3) * n + 23 - 12 * sqrt3
    ) / 36
    interaction = -(6 * n**2 + 6 * n + 1) / 72
    assert sp.simplify(delta4 - expected4) == 0
    assert sp.simplify(delta3 - expected3) == 0
    assert sp.simplify(delta4 + delta3 - interaction) == 0

    # Solve r^3+delta*r=eta with eta=eps^-3 far enough for E at eps^2.
    r = eps**-1 - delta * eps / 3 + delta**3 * eps**5 / 81
    assert sp.series(r**3 + delta * r - eps**-3, eps, 0, 5) == sp.O(eps**5)
    A = 2 * r**2 + delta
    omega = sp.sqrt(A**2 - r**4)
    quadratic = (
        -sp.Rational(3, 2) * r**4 - delta * r**2
        + omega * (n + sp.Rational(1, 2)) - A / 2
    )
    quadratic_series = sp.series(quadratic, eps, 0, 3)
    quadratic_constant = delta * (1 - 2 * delta) / 6
    assert sp.simplify(
        sp.expand(quadratic_series.removeO()).coeff(eps, 0)
        - quadratic_constant
    ) == 0

    constant = sp.simplify(quadratic_constant + interaction)
    candidate = delta * (1 - 2 * delta) / 6 - (6*n**2 + 6*n + 1) / 72
    assert sp.simplify(constant - candidate) == 0

    spacing_constant = sp.expand(candidate.subs(n, n + 1) - candidate)
    anharmonicity_constant = sp.expand(
        candidate.subs(n, n + 2) - 2 * candidate.subs(n, n + 1) + candidate
    )
    assert sp.simplify(spacing_constant + (n + 1) / 6) == 0
    assert sp.simplify(anharmonicity_constant + sp.Rational(1, 6)) == 0

    return {
        "delta4": sp.expand(delta4),
        "delta3": sp.expand(delta3),
        "interaction_sum": interaction,
        "quadratic_series": quadratic_series,
        "energy_constant": candidate,
        "spacing_constant": spacing_constant,
        "anharmonicity_constant": anharmonicity_constant,
        "o3_shifts": tuple(sorted(o3)),
        "o4_shifts": tuple(sorted(o4)),
    }


if __name__ == "__main__":
    for name, value in corrections().items():
        print(f"{name} = {value}")
